name: speechmate
description: "A bilingual Dictionary for Nicobarian translation"
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  audioplayers: ^6.5.1
  shared_preferences: ^2.2.2
  # speech_to_text: ^6.6.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_main.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/icons/logo_main.png
  branding: assets/icons/branding.png
  color: "#ffffff"
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: assets/icons/logo_main.png
    branding: assets/icons/branding.png
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/data/dictionary.json
    - assets/icons/logo_main.png
    - assets/audio/numbers/
    - assets/audio/phrases/
    - assets/audio/nature/
    - assets/audio/body_parts/
    - assets/audio/feelings/
    - assets/images/
    - assets/data/dictionary_phrases.json
    - assets/icons/branding.png

