name: speechmate
description: "A bilangual Dictionary for Nicobarian translation"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  image: assets/icons/logo.png
  color: "#015ed4"
  android: true
  ios: true
  android_12:
    color: "#015ed4"

  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/data/dictionary.json
    - assets/icons/logo.png